In [673]:
%matplotlib inline
from sklearn.cross_validation import KFold
from sklearn.metrics import roc_curve, roc_auc_score

In [674]:
import random
np.random.seed(123)
vars=np.random.choice(40,10,False)

In [675]:
np.append(0,vars)

array([ 0,  6, 10, 12, 38,  5, 11, 23,  1, 13, 20])

In [676]:
import itertools
np.random.seed(99)
ab = itertools.chain(list(zip(np.random.dirichlet([1,1],15).tolist(),np.random.dirichlet([1,1],15).tolist())),
                     list(zip(np.random.dirichlet([1,1,1],5).tolist(),np.random.dirichlet([1,1,1],5).tolist())), 
                     list(zip(np.random.dirichlet([1,1,1,1],5).tolist(),np.random.dirichlet([1,1,1,1],5).tolist())),
                     list(zip(np.random.dirichlet([1,1,1],5).tolist(),np.random.dirichlet([1,1,1],5).tolist())),
                     list(zip(np.random.dirichlet([1,1,1,1,1],5).tolist(),np.random.dirichlet([1,1,1,1,1],5).tolist())),
                     list(zip(np.random.dirichlet([1,1,1,1,1,1],5).tolist(),np.random.dirichlet([1,1,1,1,1,1],5).tolist())))

In [677]:
phi=np.array(list(ab))
phi

array([[[0.6249198216400619, 0.37508017835993795],
        [0.3946604132086852, 0.6053395867913146]],
       [[0.9820270769942365, 0.017972923005763513],
        [0.8890698404664713, 0.1109301595335287]],
       [[0.6643670634209644, 0.3356329365790356],
        [0.976049914253328, 0.02395008574667222]],
       [[0.8807766255007131, 0.11922337449928692],
        [0.7401912482273242, 0.2598087517726758]],
       [[0.9985355125997742, 0.0014644874002257002],
        [0.06487265150286255, 0.9351273484971374]],
       [[0.5167704752798782, 0.48322952472012193],
        [0.9482168688515075, 0.051783131148492666]],
       [[0.41016433506604055, 0.5898356649339594],
        [0.42133915624052337, 0.5786608437594766]],
       [[0.8401088541206045, 0.1598911458793955],
        [0.4723812136551637, 0.5276187863448362]],
       [[0.8307499014424404, 0.1692500985575596],
        [0.07782291591332545, 0.9221770840866744]],
       [[0.05532464958329419, 0.9446753504167058],
        [0.671841665994798

In [678]:
phi[np.append(0,vars)]

array([[[0.6249198216400619, 0.37508017835993795],
        [0.3946604132086852, 0.6053395867913146]],
       [[0.41016433506604055, 0.5898356649339594],
        [0.42133915624052337, 0.5786608437594766]],
       [[0.22738382459255063, 0.7726161754074493],
        [0.6272286545128304, 0.3727713454871695]],
       [[0.8754418562842615, 0.12455814371573852],
        [0.6064318954749228, 0.3935681045250772]],
       [ [0.00919358428028653, 0.20747920140171133, 0.03339837121186943, 0.34122023576895416, 0.2405560276532923, 0.1681525796838864],
        [0.2069360430021255, 0.3302244053320049, 0.07452659856437703, 0.20398359602819074, 0.17281882367453633, 0.01151053339876546]],
       [[0.5167704752798782, 0.48322952472012193],
        [0.9482168688515075, 0.051783131148492666]],
       [[0.16951597494463866, 0.8304840250553612],
        [0.08442669621408619, 0.915573303785914]],
       [ [0.11450255937257463, 0.04534063926551845, 0.8228927337009636, 0.01726406766094343],
        [0.1609275031

In [680]:
np.random.seed(121)
alpha=np.random.dirichlet((0.1, 2), 10)
alpha

array([[  2.83963133e-10,   1.00000000e+00],
       [  1.09922548e-04,   9.99890077e-01],
       [  5.44714744e-07,   9.99999455e-01],
       [  7.59398447e-02,   9.24060155e-01],
       [  1.19911030e-06,   9.99998801e-01],
       [  1.73448720e-06,   9.99998266e-01],
       [  4.01973309e-02,   9.59802669e-01],
       [  1.73903029e-04,   9.99826097e-01],
       [  8.06482400e-09,   9.99999992e-01],
       [  4.74146069e-01,   5.25853931e-01]])

In [681]:
np.random.multinomial(1,alpha[4],1)[0]

array([0, 1])

In [683]:
profiles=[]
np.random.seed(121)
for i in range(10):
    profiles.append(np.random.multinomial(1,alpha[i],1)[0][1])
profiles

[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]

In [840]:
y=np.zeros(40)
for i in range(1000):
    cd=itertools.chain(np.random.choice(2,15).tolist(),np.random.choice(3,5).tolist(),np.random.choice(4,5).tolist(),
                   np.random.choice(3,5).tolist(),np.random.choice(5,5).tolist(),np.random.choice(6,5))
    cd=np.array(list(cd))
    real_data=[]
    for i in range(10):
        real_data.append(np.where(np.random.multinomial(1, phi[vars][i][profiles[i]], size=1)==1)[1].tolist())
    real_data=sum(real_data,[])
    
    y=np.vstack([y,np.array(list(cd))])
    
    

In [841]:
y.shape

(1001, 40)

In [842]:
y=np.delete(y,0,0)

In [843]:
y=np.transpose(y)

In [844]:
y.shape

(40, 1000)

In [845]:
test=y[vars]

In [846]:
def profile_class(data,phi,NumProf):
    """This function calculates the GoM scores for each individual
        Parameters:
        Input: data and phi calculate from MELD
           Output: GoM score
        """
    score=np.zeros([data.shape[1],NumProf])
    profile=np.zeros([int(data.shape[0]),int(data.shape[1])])
    for j in range(data.shape[1]):
        for i in range(data.shape[0]):
            yij=int(data[i,j])
            #calculate M_ij
            profile[i,j]=np.argmax(np.array(list(phi[i]))[:,yij])
            if profile[i,j]==0:
                score[j,0]=score[j,0]+1
            else:
                score[j,1]=score[j,1]+1
        score[j,:]=(score[j,:]+0.1)/(phi.shape[0]+0.2)
    return score


In [847]:
phi[np.append(0,vars)][1:].shape

(10, 2)

In [848]:
gscore=profile_class(test,phi[vars],2)
# calculate risk
risk=gscore[:,None]*np.transpose(np.array(list(phi[0])))
risk=np.sum(risk[:,1,:],axis=1)
risk
   

array([ 0.51278433,  0.53535879,  0.51278433,  0.51278433,  0.49020988,
        0.55793324,  0.49020988,  0.51278433,  0.46763543,  0.46763543,
        0.51278433,  0.51278433,  0.46763543,  0.49020988,  0.44506098,
        0.53535879,  0.46763543,  0.49020988,  0.51278433,  0.55793324,
        0.49020988,  0.51278433,  0.44506098,  0.46763543,  0.51278433,
        0.46763543,  0.49020988,  0.51278433,  0.53535879,  0.53535879,
        0.51278433,  0.51278433,  0.46763543,  0.46763543,  0.46763543,
        0.46763543,  0.49020988,  0.44506098,  0.46763543,  0.46763543,
        0.53535879,  0.55793324,  0.53535879,  0.51278433,  0.46763543,
        0.51278433,  0.49020988,  0.46763543,  0.55793324,  0.51278433,
        0.46763543,  0.53535879,  0.44506098,  0.51278433,  0.51278433,
        0.46763543,  0.46763543,  0.46763543,  0.44506098,  0.51278433,
        0.53535879,  0.44506098,  0.55793324,  0.51278433,  0.44506098,
        0.51278433,  0.49020988,  0.51278433,  0.44506098,  0.51

In [849]:
np.place(risk,risk<0.5,0)

In [850]:
np.place(risk,risk>=0.5,1)

In [851]:
risk

array([ 1.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,
        0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,
        0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,
        0.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,
        1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,
        0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,
        0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,
        0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,
        0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,
        1.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,
        1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  0

In [852]:
y[0]=risk

In [853]:
def MELD_Backward_features(data, Numfolds, features, NumProf):
    """This function performs supervised MELD and backward elimination algorithm
    Parameters:
        Input: a dataframe and number of folds
        output: select maximum AUC and corresponding features 
        for every specific number of features  
    """
    #divide data into kf cross validation folds
    kf=KFold(data.shape[1],Numfolds,shuffle=False,random_state=111)
    
    def profile_class(data,phi):
        """This function calculates the GoM scores for each individual
        Parameters:
        Input: data and phi calculate from MELD
           Output: GoM score
        """
        score=np.zeros([data.shape[1],NumProf])
        profile=np.zeros([int(data.shape[0]),int(data.shape[1])])
        for j in range(data.shape[1]):
            for i in range(data.shape[0]):
                yij=int(data[i,j])
                #calculate M_ij
                profile[i,j]=np.argmax(phi[i][:,yij])
                if profile[i,j]==0:
                    score[j,0]=score[j,0]+1
                else:
                    score[j,1]=score[j,1]+1
            score[j,:]=(score[j,:]+0.1)/(phi.shape[0]+0.1*NumProf)
        return score
    
    #create a list of features
    vec_list=[]
    for j in range(len(features)-1):
        integers=features[:]
        del integers[j+1]
        vec_list.append(integers)
    
    auc_list_outer=[]
    #whole_gom_list=[]
    for j in range(len(vec_list)):
        auc_list=[]
        #gom_list=[]
        vec=vec_list[j]
        for i in range(Numfolds):
            train=data[:,list(kf)[i][0]]
            test=data[:,list(kf)[i][1]]
            import sim as MELD
            k=NumProf
            S=100
            Y = train
            (p,n) = Y.shape
            Yt = np.array([0]*p)
            Yt[0]=0
            # create an object of MELD class
            myMELD = MELD.MELD(Y,Yt,k,vec)
            # calculate second moment matrices
            myMELD.calM2()
            myMELD.calM2_bar()
            # ------------- first stage
            # initialize weight matrices to identity
            myMELD.initializeWeight_M2()
            # perform first stage estimation
            Result1 = myMELD.estimatePhiGrad_M2(S)
            # extract phi from the result
            phi1=Result1['PHI'][Result1['iter']]
            # extract selected features in the test fold
            test=test[vec]
            # calculate GoM score
            gscore=profile_class(test[1:],phi1[1:])
            # calculate risk
            risk=gscore[:,None]*np.transpose(phi1[0])
            risk=np.sum(risk[:,1,:],axis=1)
            #gom_list.append(gscore[:,1])
            # replace 0 with label "-1"
            np.place(test[0],test[0]==0,[-1])
            # calculate AUC
            auc = roc_auc_score(test[0],risk)
            auc_list.append(auc)
        #calculate the mean AUC across kf folds
        auc_new=np.mean(auc_list)
        auc_list_outer.append(auc_new)
        #whole_gom_list.append(list(np.concatenate(gom_list)))
        
    auc_all=[]
    vec_all=[]
    #gom_all=[]
    while len(vec_list)>2:
        vec_list_2=vec_list[np.argmax(auc_list_outer).astype(int)] 
        #gom_list_2=whole_gom_list[np.argmax(auc_list_outer).astype(int)]
        vec_all.append(vec_list_2)
        #gom_all.append(gom_list_2)
        vec_list=[]
        #whole_gom_list=[]
        #eliminate one feature at a time
        for k in range(len(vec_list_2)-1):
            integers=vec_list_2[:]
            del integers[k+1]
            vec_list.append(integers)

        auc_list_outer=[] 
       
        for j in range(len(vec_list)):
            auc_list=[]
            #gom_list=[]
            vec=vec_list[j]

            for i in range(10):
            
                train=data[:,list(kf)[i][0]]
    
                test=data[:,list(kf)[i][1]]
        
                import sim as MELD
                k=NumProf
                S=100

                Y = train
                (p,n) = Y.shape

                Yt = np.array([0]*p)
                Yt[0]=0
                # create an object of MELD class
                myMELD = MELD.MELD(Y,Yt,k,vec)

                # calculate second moment matrices
                myMELD.calM2()
                myMELD.calM2_bar()

                # ------------- first stage
                # initialize weight matrices to identity
                myMELD.initializeWeight_M2()

                # perform first stage estimation
                Result1 = myMELD.estimatePhiGrad_M2(S)
                # extract phi from the result
                phi1=Result1['PHI'][Result1['iter']]
                # extract selected features from test fold
                test=test[vec]
                # calculate GoM score
                gscore=profile_class(test[1:],phi1[1:])
                # calculate risk
                risk=gscore[:,None]*np.transpose(phi1[0])
                risk=np.sum(risk[:,1,:],axis=1)
                #gom_list.append(gscore[:,1])
                # replace 0 with label "-1"
                np.place(test[0],test[0]==0,[-1])
                # calculate AUC
                auc = roc_auc_score(test[0],risk)
                auc_list.append(auc)
            # calculate average AUC across kf folds
            auc_new=np.mean(auc_list)     
            auc_list_outer.append(auc_new)
            #whole_gom_list.append(list(np.concatenate(gom_list)))
              
        
        # selected the maximum AUC from a list of AUC's
        auc_new_new=max(auc_list_outer)
    
        auc_all.append(auc_new_new)
        
        auc=np.max(auc_all)
        
        feature_selected=vec_all[np.argmax(auc_all)]
        
        #gom=gom_all[np.argmax(auc_all)]
    
    return auc, feature_selected

In [854]:
out_2=MELD_Backward_features(y, 10, list(range(y.shape[0])), 2)

/Users/wsswemily/Desktop/SMELD/sim.py:70: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  Y_j = np.zeros((n,self.d[j]))
/Users/wsswemily/Desktop/SMELD/sim.py:72: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  Y_j[i,Y[j,i]] = 1
/Users/wsswemily/Desktop/SMELD/sim.py:74: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self.Phi[j] = np.zeros((k,self.d[j]))
/Users/wsswemily/Desktop/SMELD/sim.py:75: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self.X[j] = np.zeros((k,self.d[j]))
/Users/wsswemily/Desktop/SMELD/sim.py:82: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self.Phi[j][h,:] = np.random.dirichlet([100.0]*self.d[j])
/Users/wsswemily/Desktop/SMELD

In [855]:
out_2  #400

(0.76557518453482576, [0, 6, 12, 13, 20])

In [856]:
vars

array([ 6, 10, 12, 38,  5, 11, 23,  1, 13, 20])

In [653]:
res=risk

In [656]:
x=np.transpose(y[1:])

In [658]:
x.shape

(400, 39)

In [25]:
import slda
from slda.topic_models import BLSLDA

ImportError: dlopen(/Applications/anaconda/lib/python3.5/site-packages/slda/_topic_models.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libgsl.19.dylib
  Referenced from: /Applications/anaconda/lib/python3.5/site-packages/slda/_topic_models.cpython-35m-darwin.so
  Reason: image not found

In [26]:
_K = 2
_alpha = alpha
_beta = np.repeat(0.01, V)
_mu = 0
_nu2 = 0.1
_b = 7.25
n_iter = 500
blslda = BLSLDA(_K, _alpha, _beta, _mu, _nu2, _b, n_iter, seed=42)

NameError: name 'alpha' is not defined